version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: openanalytics
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: sidharthchauhan/backend-trackly:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: Trackly
      JWT_SECRET: supersecretkey
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: sidharthchauhan/frontend-trackly:latest
    environment:
      VITE_BACKEND_URL: http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - db
      - backend
    restart: unless-stopped

volumes:
  postgres-data:
